### ISSUE TITLE
Shipment create via API salesShipmentRepositoryV1 throw Fatal error

### ISSUE THREAD

**Issue by milindsingh** [magento-engcom/msi#2220]
### Preconditions (*)

1. Magento 2.3.1 with MSI enabled
2. Single Default Source for Inventory
3. The order created from Admin Panel

### Steps to reproduce (*)

1.  Create an order created from Admin Panel
2. Create Shipment via API:

```json
{
  "entity": {
    "increment_id": "000000003",
    "order_id": 3,
    "items": [
        {
          "sku": "WSH12-32-Red",
          "qty": 1
        }
      ],
    "tracks": [
      {
        "order_id": 3,
        "qty": 1,
        "track_number": "123",
        "title": "Test",
        "carrier_code": "dhl"
      }
    ]  
  }
}
```

### Expected result (*)

1. Shipment is created in Admin

### Actual result (*)

1. Fatal Error
```json
can't parse JSON.  Raw result:

<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given, called in /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-sales/Model/GetSkuFromOrderItem.php on line 48 and defined in /opt/lampp7.2/htdocs/magento/2.3.sample/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
Stack trace:
#0 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-sales/Model/GetSkuFromOrderItem.php(48): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor-&gt;execute(NULL)
#1 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-shipping/Model/GetItemsToDeductFromShipment.php(75): Magento\InventorySales\Model\GetSkuFromOrderItem-&gt;execute(Object(Magento\Sales\Model\Order\Item\Interceptor))
#2 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module- in <b>/opt/lampp7.2/htdocs/magento/2.3.sample/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php</b> on line <b>20</b><br />
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/398581820999"}]}}
```

Note: **Works after disabling the MSI modules.**

**Comment by IvanPletnyov** [comment]
@milindsingh Hello! I check this issue and I noticed one mistake in your request body. Could you please add field "order_item_id" to items (it must work properly)
For example:
_{"entity": {"increment_id": "000000003","order_id": 3,"items": [{ "order_item_id": 3,"qty": 1}],"tracks": [{"order_id": 3, "qty": 1,"track_number": "123","title": "Test","carrier_code": "dhl" }]}}_

**Comment by milindsingh** [comment]
@ishakhsuvarov 
Yes, you are correct that by providing the  "order_item_id" the issue doesn't occur.
But I think the API should have a basic validation check of data sent for shipment?
Is data validation not done intentionally?

**Comment by ishakhsuvarov** [comment]
@milindsingh Yes, I guess this is something we should investigate and figure out the best fix. It might be more of a core issue however.
